# Generated by Django 3.2 on 2023-04-01 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210709_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 1, 13, 2, 34, 460237), null=True),
        ),
    ]
